# Autogenerated by devscripts/update-version.py

__version__ = '2024.03.25.045354'

RELEASE_GIT_HEAD = '92f8387ecbadaf00695c62eb256a12b051c86679'

VARIANT = None

UPDATE_HINT = None

CHANNEL = 'fsan1999/yt-dlp-d'

ORIGIN = 'fsan1999/yt-dlp-d'

_pkg_version = '2024.03.25.045354'
