# Autogenerated by devscripts/update-version.py

__version__ = '2024.03.21.033543'

RELEASE_GIT_HEAD = '96fcbae841ddf368236bb75e31fe9f89c5e80afb'

VARIANT = None

UPDATE_HINT = None

CHANNEL = 'fsan1999/yt-dlp-d'

ORIGIN = 'fsan1999/yt-dlp-d'

_pkg_version = '2024.03.21.033543'
