# Autogenerated by devscripts/update-version.py

__version__ = '2023.11.19.150016'

RELEASE_GIT_HEAD = '585d0ed9abcfcb957f2b2684b8ad43c3af160383'

VARIANT = None

UPDATE_HINT = None

CHANNEL = 'scientiacoder/yt-dlp'

ORIGIN = 'scientiacoder/yt-dlp'

_pkg_version = '2023.11.19.150016'
